name: 'GitHub Actions Weather Bot'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  get-weather:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      
      - name: Install Requirements
        run: |
          pip3 install -U -r requirements.txt

      - name: 'Get Date'
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      
      - name: 'Get Weather'
        run: |
          echo ${{env.REPORT_DATE}}
          python3 main.py -t="${{env.REPORT_DATE}}"
          mkdir site
          cp index.html site/index.html
          
      - name: Minify HTML
        uses: Dup4/minify-html-action@v9
        with:
          src: './site/index.html'

#      - name: 'Send mail'
#        uses: dawidd6/action-send-mail@master
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          username: ${{ secrets.MAIL_USERNAME }}
#          password: ${{ secrets.MAIL_PASSWORD }}
#          subject: Weather Report (${{env.REPORT_DATE}})
#          body: file://index.html
#          to: lyuzhi.pan@gmail.com
#          from: Weather Bot
#          content_type: text/html

      - name: Release
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: site 
          clean: true
          clean-exclude: CNAME