name: 'GitHub Actions Weather Bot'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  get-weather:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: 'x64' # (x64 or x86)
      
      - name: 'Install requirements'
        run: |
          pip3 install -U -r requirements.txt

      - name: 'Get Weather'
        run: |
          python3 main.py > index.html
          mkdir site
          cp index.html site/index.html

      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

#      - name: 'Send mail'
#        uses: dawidd6/action-send-mail@master
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          username: ${{ secrets.MAIL_USERNAME }}
#          password: ${{ secrets.MAIL_PASSWORD }}
#          subject: Weather Report (${{env.REPORT_DATE}})
#          body: file://index.html
#          to: lyuzhi.pan@gmail.com
#          from: Weather Bot
#          content_type: text/html

      - name: Release
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
